.TH "OPENCV_TRAINCASCADE" "1" "May 2010" "OpenCV" "User Commands"


.SH NAME
opencv_traincascade \- transcascade application



.SH SYNOPSIS
.B opencv_traincascade [options]


.SH DESCRIPTION
.PP
.B traincascade application.

.SH OPTIONS

.PP
.B opencv_traincascade
supports the following options:

.SH BASIC OPTIONS

.TP
.BI "\-data " cascade_dir_name

.TP  
.BI "\-vec " vec_file_name

.TP
.BI "\-bg " background_file_name

.TP
.BI "\-numPos " number_of_positive_samples
The default is
.IR 2000 .

.TP
.BI "\-numNeg " number_of_negative_samples
The default is
.IR 1000 .

.TP
.BI "\-num " Stages number_of_stages 
The default is
.IR 20 .

.TP
.BI "\-precalcValBufSize " precalculated_vals_buffer_size_in_Mb
The default is
.IR 256 .

.TP
.BI "\-precalcIdxBufSize " precalculated_idxs_buffer_size_in_Mb
The default is
.IR 256 .

.TP
.BI "\-baseFormatSave "

.SH CASCADE OPTIONS
 
.TP
.BI "\-stageType "
The default is
.IR BOOST .

.TP
.BI "\-featureType "
Set feature type . You can select HAAR or LBP.
The default is
.IR HAAR .

.TP
.BI "\-w " sampleWidth
The default is
.IR 24 .

.TP
.BI "\-h " sampleHeight
The default is
.IR 24 .

.SH BOOST OPTIONS

.TP
.BI "\-bt {" DAB | RAB | LB | GAB "}"
The type of the applied boosting algorithm. You can choose between Discrete
AdaBoost (\fIDAB\fR), Real AdaBoost (\fIRAB\fR), LogitBoost (\fILB\fR) and
Gentle AdaBoost (\fIGAB\fR). The default is
.IR GAB .

.TP
.BI "\-minHitRate " min_hit_rate
The default is
.IR 0.995 .

.TP
.BI "\-maxFalseAlarmRate " max_false_alarm_rate
The default is
.IR 0.5 .

.TP
.BI "\-weightTrimRate " weight_trim_rate
The default is
.IR 0.95 .

.TP
.BI "\-maxDepth " max_depth_of_weak_tree
The default is
.IR 1 .

.TP
.BI "\-maxWeakCount " max_weak_tree_count
The default is
.IR 100 .

.SH HAARFEATURE OPTIONS

.TP
.BI "\-mode " <BASIC | CORE | ALL>
The type of the applied haarFeature mode. You can choose between \fIBASIC\fR, 
\fCORE\fR and \fIALL\fR. The default is
.IR BASIC .

.SH EXAMPLES
.PP
TODO

.SH SEE ALSO
.PP
.BR opencv_haartraing (1),
.BR opencv_performance (1)
.PP
More information and examples can be found in the OpenCV documentation.


.SH AUTHORS
.PP
This manual page was written by \fBNobuhiro Iwamatsu\fR <\&iwamatsu@debian.org\&>
for the Debian project (but may be used by others).
