#!/bin/sh
#
# see: dh_installdeb(1)

set -e

if [ -f /lib/firmware/ti-connectivity/wl18xx-fw-4.bin ] ; then
	rm -f /lib/firmware/ti-connectivity/wl18xx-fw-4.bin || true
	cp -v /lib/firmware/ti-connectivity/git/wl18xx-fw-4.bin /lib/firmware/ti-connectivity/wl18xx-fw-4.bin
else
	cp -v /lib/firmware/ti-connectivity/git/wl18xx-fw-4.bin /lib/firmware/ti-connectivity/wl18xx-fw-4.bin
fi

if [ ! -f /etc/systemd/network/wlan0.network ] ; then
	cp -v /etc/bbb.io/templates/wlan0-DHCP.network /etc/systemd/network/wlan0.network
fi

if [ ! -f /etc/wpa_supplicant/wpa_supplicant-wlan0.conf ] ; then
	cp -v /etc/bbb.io/templates/wpa_supplicant-wlan0.conf /etc/wpa_supplicant/wpa_supplicant-wlan0.conf
fi

case "$1" in
	configure)
		if [ -x /usr/sbin/update-initramfs -a -e /etc/initramfs-tools/initramfs.conf ] ; then
			update-initramfs -u
		fi
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#

exit 0

