.TH DTC 1 "30 January 2012" "Linux"
.SH NAME
\fBdtdiff\fP \- compare two different device-tree
.SH SYNOPSIS
\fB/usr/bin/dtdiff\fP <device tree> <device tree>
.SH DESCRIPTION
Compares two different device-tree.
.SH AUTHOR
\fBdtc\fP was written by David Gibson
<david@gibson.dropbear.id.au>. Since April 1, 2006, Jon Loeliger
<jdl@jdl.com> assumes maintainership.
.PP
This manual page was written by H\['e]ctor Or\['o]n
<zumbi@debian.org>, for the Debian project (but may be used by others).
