#!/bin/sh
# postrm script for #PACKAGE#
#
# see: dh_installdeb(1)

set -e

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        [ -d /var/lib/connman ] && rm -rf /var/lib/connman
        [ -L /etc/resolv.conf ] && rm -f /etc/resolv.conf
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
