.\"                                      Hey, EMACS: -*- nroff -*-
.TH GO-RUN 1 "2012-05-13"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
go \- tool for managing Go source code
.SH SYNOPSIS
.B go run
.RB [
.IR "build flags"
.RB ]
.IR gofiles...
.RB [
.IR arguments...
.RB ]
.SH DESCRIPTION
Run compiles and runs the main package comprising the named Go source files.
.P
For more about build flags, see \fBgo-build\fP(1).
.SH SEE ALSO
.BR go-build (1).
.SH AUTHOR
.PP
This manual page was written by Michael Stapelberg <stapelberg@debian.org>,
for the Debian project (and may be used by others).
