.\"                                      Hey, EMACS: -*- nroff -*-
.TH GO-TOOL 1 "2012-05-13"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
go \- tool for managing Go source code
.SH SYNOPSIS
.B go tool
.RB [\|\-n\|]
.IR command
.RB [
.IR args...
.RB ]
.SH DESCRIPTION
Tool runs the go tool command identified by the arguments.
With no arguments it prints the list of known tools.
.SH OPTIONS
.TP
.B \-n
The \-n flag causes tool to print the command that would be
executed but not execute it.
.P
For more about each tool command, see 'go tool command \-h'.
.SH AUTHOR
.PP
This manual page was written by Michael Stapelberg <stapelberg@debian.org>,
for the Debian project (and may be used by others).
