.\"                                      Hey, EMACS: -*- nroff -*-
.TH GO-VET 1 "2012-06-15"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
go \- tool for managing Go source code
.SH SYNOPSIS
.B go vet
.RB [\|\-n\|]
.RB [\|\-x\|]
.RB [
.IR packages
.RB ]
.SH DESCRIPTION
Vet runs the Go vet command on the packages named by the import paths.
.P
For more about vet, see 'godoc vet'.
.P
For more about specifying packages, see \fBgo-packages\fP(7).
.P
To run the vet tool with specific options, run 'go tool vet'.
.SH OPTIONS
.TP
.B \-n
The \-n flag causes tool to print the command that would be
executed but not execute it.
.TP
.B \-x
The \-x flag causes clean to print remove commands as it executes them.
.SH SEE ALSO
.BR go-fmt (1),
.BR go-fix (1).
.SH AUTHOR
.PP
This manual page was written by Michael Stapelberg <stapelberg@debian.org>,
for the Debian project (and may be used by others).
