.\"                                      Hey, EMACS: -*- nroff -*-
.TH GO 1 "2012-05-13"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
go \- tool for managing Go source code
.SH SYNOPSIS
.B go
.RI command
.RI [ arguments ]
.SH DESCRIPTION
The Go distribution includes a command, named \fBgo\fP, that automates the
downloading, building, installation, and testing of Go packages and commands.
.SH COMMANDS
Each command is documented in its own manpage. For example, the \fBbuild\fP
command is documented in \fBgo-build\fP(1). The commands are:
.TP
.B build
compile packages and dependencies
.TP
.B clean
remove object files
.TP
.B doc
run godoc on package sources
.TP
.B env
print Go environment information
.TP
.B fix
run go tool fix on packages
.TP
.B fmt
run gofmt on package sources
.TP
.B get
download and install packages and dependencies
.TP
.B install
compile and install packages and dependencies
.TP
.B list
list packages
.TP
.B run
compile and run Go program
.TP
.B test
test packages
.TP
.B tool
run specified go tool
.TP
.B version
print Go version
.TP
.B vet
run go tool vet on packages
.SH EXAMPLES
TODO
.SH SEE ALSO
.BR go-build (1),
.BR go-clean (1).
.SH AUTHOR
.PP
This manual page was written by Michael Stapelberg <stapelberg@debian.org>,
for the Debian project (and may be used by others).
