Document: bela-customizations
Title: Debian bela-customizations Manual
Author: <insert document author here>
Abstract: This manual describes what bela-customizations is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bela-customizations/bela-customizations.sgml.gz

Format: postscript
Files: /usr/share/doc/bela-customizations/bela-customizations.ps.gz

Format: text
Files: /usr/share/doc/bela-customizations/bela-customizations.text.gz

Format: HTML
Index: /usr/share/doc/bela-customizations/html/index.html
Files: /usr/share/doc/bela-customizations/html/*.html
