#!/bin/sh

set -e

groupadd gpio --system || true

check_n_ln () {
	if [ ! -f /lib/firmware/${wfirm} ] ; then
		ln -sf /lib/firmware/${wfirm}.sleep /lib/firmware/${wfirm}
		/bin/chgrp gpio /lib/firmware/${wfirm}
		/bin/chmod g=u /lib/firmware/${wfirm}
	fi
}

wfirm="am335x-pru0-fw" ; check_n_ln
wfirm="am335x-pru1-fw" ; check_n_ln
wfirm="am57xx-pru1_0-fw" ; check_n_ln
wfirm="am57xx-pru1_1-fw" ; check_n_ln
wfirm="am57xx-pru2_0-fw" ; check_n_ln
wfirm="am57xx-pru2_1-fw" ; check_n_ln

case "$1" in
	configure)
		net_rcnee=$(cat /etc/apt/sources.list | grep repos.rcn-ee.net || true)
		if [ ! "x${net_rcnee}" = "x" ] ; then
			sed -i -e 's:repos.rcn-ee.net:repos.rcn-ee.com:g' /etc/apt/sources.list
		fi

		if [ -x /usr/sbin/update-initramfs -a -e /etc/initramfs-tools/initramfs.conf ] ; then
			update-initramfs -u
		fi
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
		echo "postinst called with unknown argument \`$1'" 1>&2
		exit 1
	;;
esac

#DEBHELPER#
