#!/bin/sh
set -euf
cat << EOF
debian/scripts/pypyclean              /usr/bin
debian/scripts/pypycompile            /usr/bin
include/pypy_*.h                      /usr/lib/pypy/include
lib_pypy/__pycache__/_cffi_*.so       /usr/lib/pypy/lib_pypy
pypy/goal/pypy-c                      /usr/lib/pypy/bin
EOF

find lib_pypy/ctypes_config_cache -type f -name '_*_.py' ! -name __init__.py \
  | sed 's,$, /usr/lib/pypy/lib_pypy/ctypes_config_cache,'
