usr/include/lxqt-globalkeys-ui/shortcutselector.h
usr/include/lxqt-globalkeys-ui/shortcut_selector.h
usr/include/lxqt-globalkeys-ui/LXQtGlobalKeysUi/ShortcutSelector

usr/lib/*/liblxqt-globalkeys-ui.so
usr/lib/*/pkgconfig/lxqt-globalkeys-ui.pc

usr/share/cmake/lxqt-globalkeys-ui/lxqt-globalkeys-ui-targets-none.cmake
usr/share/cmake/lxqt-globalkeys-ui/lxqt-globalkeys-ui-config.cmake
usr/share/cmake/lxqt-globalkeys-ui/lxqt-globalkeys-ui-config-version.cmake
usr/share/cmake/lxqt-globalkeys-ui/lxqt-globalkeys-ui-targets.cmake
