#!/bin/sh

set -e

# Folders
J_INSTALL_DIR=/usr/lib/jvm/java-9-oracle/lib/security/
J_POLICY_DIR=/usr/lib/jvm/java-9-oracle/lib/security/unlimited_policy

# Copy it to the right dir
if [ -e /usr/lib/jvm/java-9-oracle/lib/security/unlimited_policy ]; then
	cp -rf ${J_POLICY_DIR}/*.jar ${J_INSTALL_DIR}
fi

echo "Unlimited JCE Policy for Oracle Java 9 istalled"

#DEBHELPER#

exit 0

# vim: ts=2 sw=2
