#!/bin/sh
#
# Wrapper script to hide distribution-specific installation
# prefixes when running standard Xenomai commands.
#
# e.g. "xeno latency"
#

prefix="/usr"
exec_prefix="${prefix}"
BINDIR="${exec_prefix}/bin"
TESTDIR="/usr/lib/xenomai/testsuite"
unset prefix exec_prefix

test -x $BINDIR/$1 && exec $BINDIR/$@
test -x $TESTDIR/$1 && exec $TESTDIR/$@
echo "$1: not found/executable"
