#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.3.4
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.3.4
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'bela_button.service' 'bela_gadget.service' 'bela_ide.service' 'bela_shutdown.service' 'bela_startup.service' 'dhclient_shutdown.service' 'ssh_shutdown.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'bela_button.service' 'bela_gadget.service' 'bela_ide.service' 'bela_shutdown.service' 'bela_startup.service' 'dhclient_shutdown.service' 'ssh_shutdown.service' >/dev/null || true
		deb-systemd-helper unmask 'bela_button.service' 'bela_gadget.service' 'bela_ide.service' 'bela_shutdown.service' 'bela_startup.service' 'dhclient_shutdown.service' 'ssh_shutdown.service' >/dev/null || true
	fi
fi
# End automatically added section
