etc/dbus-1/system.d/connman.conf
lib/systemd/system/connman.service
lib/systemd/system/connman-wait-online.service

usr/share/man
usr/share/polkit-1/actions/net.connman.policy
usr/bin/connmanctl /usr/sbin
usr/lib/tmpfiles.d/connman_resolvconf.conf
usr/sbin/connmand
usr/sbin/connmand-wait-online

debian/source_connman.py /usr/share/apport/package-hooks/
debian/connman-crashdb.conf /etc/apport/crashdb.conf.d/
