debian/81-add-SoftAp0-interface.rules /etc/udev/rules.d/
debian/82-SoftAp0-start-hostpad.rules /etc/udev/rules.d/
debian/SoftAp0-DHCPServer.network /etc/bbb.io/templates/
debian/bb-hostapd.conf /etc/bbb.io/templates/
debian/wlan0-DHCP.network /etc/bbb.io/templates/
debian/wpa_supplicant-wlan0.conf /etc/bbb.io/templates/
debian/wpa_supplicant-mesh0.conf /etc/bbb.io/templates/
debian/81-add-mesh0-interface.rules /etc/bbb.io/templates/
