#!/bin/sh

set -e

service="bb-code-server"

# drop the temporary mask from prerm
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	systemctl unmask --runtime ${service}.service || true
fi

#DEBHELPER#

exit 0
