.TH INSPECT "1" "July 2009" "inspect " "User Commands"
.SH NAME
inspect \- Boost code inspection tool
.SH SYNOPSIS
.B inspect
[\fI-cvs\fR] [\fI-text\fR] [\fI-brief\fR] [\fIoptions\fR...]
.SH DESCRIPTION
It is not uncommon for various common errors or guideline violations
to creep into the Boost libraries. The 
.B inspect 
program detects and
reports several common problems. It can be used to scan a proposed
Boost submission to identify various failures.
.PP
The program is run in the directory to be scanned for
errors. Sub-directories are also included in the scan.
.PP
If the first program argument is -cvs, only files and directories in
the CVS tree of the current directory are scanned. Otherwise all files
and sub-directories are included in the scan.
.IP
Options:
.HP
\fB\-license\fR
.HP
\fB\-copyright\fR
.HP
\fB\-crlf\fR
.HP
\fB\-link\fR
.HP
\fB\-path_name\fR
.HP
\fB\-tab\fR
.HP
\fB\-ascii\fR
.HP
\fB\-minmax\fR
.HP
\fB\-unnamed\fR
.IP
The default is to have all checks on; otherwise options specify desired checks.
.SH "SEE ALSO"
The full documentation for
.B inspect
is maintained in HTML; 
see /usr/share/doc/libboostX.Y-doc/HTML/tools/inspect/index.html
