.TH PYSTE "1" "March 2008" "Pyste version 0.9.30" "User Commands"

.SH NAME
Pyste \- Boost.Python code generator

.SH SYNOPSIS
pyste [options] interface\-files

.SH DESCRIPTION

Pyste is a Boost.Python code generator. The user specifies the classes
and functions to be exported using a simple interface file which,
following the Boost.Python's philosophy, is simple Python code. Pyste
then uses GCCXML to parse all the headers and extract the necessary
information to automatically generate C++ code.

.TP
\fB\-\-module=\fR<name>
The name of the module that will be generated;
defaults to the first interface filename, without
the extension.
.TP
\fB\-I\fR <path>
Add an include path
.TP
\fB\-D\fR <symbol>
Define symbol
.TP
\fB\-\-multiple\fR
Create various cpps, instead of only one
(useful during development)
.TP
\fB\-\-out=\fR<name>
Specify output filename (default: <module>.cpp)
in \fB\-\-multiple\fR mode, this will be a directory
.TP
\fB\-\-no\-using\fR
Do not declare "using namespace boost";
use explicit declarations instead
.TP
\fB\-\-pyste\-ns=\fR<name>
Set the namespace where new types will be declared;
default is the empty namespace
.TP
\fB\-\-debug\fR
Writes the xml for each file parsed in the current
directory
.TP
\fB\-\-cache\-dir=\fR<dir>
Directory for cache files (speeds up future runs)
.TP
\fB\-\-only\-create\-cache\fR
Recreates all caches (doesn't generate code).
.TP
\fB\-\-generate\-main\fR
Generates the _main.cpp file (in multiple mode)
.TP
\fB\-\-file\-list\fR
A file with one pyste file per line. Use as a
substitute for passing the files in the command
line.
.TP
\fB\-\-gccxml\-path=\fR<path>
Path to gccxml executable (default: gccxml)
.TP
\fB\-\-no\-default\-include\fR
Do not use INCLUDE environment variable for include
files to pass along gccxml.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print this help and exit
.TP
\fB\-v\fR, \fB\-\-version\fR
Print version information

.SH "SEE ALSO"

The full documentation for
.B Pyste
is maintained in HTML format.  If you have the 
.B libboost-doc
package installed, the manual starts at
.IP
.B /usr/share/doc/libboost-doc/HTML/libs/python/pyste/index.html
