.TH QUICKBOOK "1" "July 2009" "Quickbook Version 1.4" "User Commands"
.SH NAME
Quickbook \- WikiWiki style documentation tool geared towards C++ documentation
.SH DESCRIPTION
.B QuickBook 
is a WikiWiki style documentation tool geared towards C++
documentation using simple rules and markup for simple formatting
tasks. 
.B QuickBook 
extends the WikiWiki concept. Like the WikiWiki,
QuickBook documents are simple text files. A single QuickBook document
can generate a fully linked set of nice HTML and PostScript/PDF
documents complete with images and syntax- colorized source code.
.PP
Features include:
.PP
    * generate BoostBook xml, to generate HTML, PostScript and PDF
    * simple markup to link to Doxygen-generated entities
    * macro system for simple text substitution
    * simple markup for italics, bold, preformatted, blurbs, code samples, tables, URLs, anchors, images, etc.
    * automatic syntax coloring of code samples
    * CSS support

.SS "Allowed options:"
.TP
\fB\-\-help\fR
produce help message
.TP
\fB\-\-version\fR
print version string
.TP
\fB\-\-no\-pretty\-print\fR
disable XML pretty printing
.TP
\fB\-\-indent\fR arg
indent spaces
.TP
\fB\-\-linewidth\fR arg
line width
.TP
\fB\-\-input\-file\fR arg
input file
.TP
\fB\-\-output\-file\fR arg
output file
.TP
\fB\-\-debug\fR
debug mode (for developers)
.TP
\fB\-\-ms\-errors\fR
use Microsoft Visual Studio style error & warn
message format
.HP
\fB\-I\fR [ \fB\-\-include\-path\fR ] arg include path
.SH "SEE ALSO"
The full documentation for
.B Quickbook
is maintained in HTML; see
/usr/share/doc/libboostX.Y-doc/HTML/doc/html/quickbook.html
