usr/include/lxqt-globalkeys-ui-qt5/shortcutselector.h
usr/include/lxqt-globalkeys-ui-qt5/shortcut_selector.h
usr/include/lxqt-globalkeys-ui-qt5/LXQtGlobalKeysUi/ShortcutSelector

usr/lib/*/liblxqt-globalkeys-ui-qt5.so
usr/lib/*/pkgconfig/lxqt-globalkeys-ui-qt5.pc

usr/share/cmake/lxqt-globalkeys-ui-qt5/lxqt_globalkeys_ui_use.cmake 
usr/share/cmake/lxqt-globalkeys-ui-qt5/lxqt-globalkeys-ui-qt5-config.cmake 
