#!/bin/sh

set -e

if [ -f /etc/systemd/timesyncd.conf ] ; then
	sed -i -e 's:#NTP=:NTP=192.168.1.24:g' /etc/systemd/timesyncd.conf
fi

if [ -f /lib/systemd/system/apt-daily.service ] ; then
	systemctl disable apt-daily.service || true
	systemctl disable apt-daily.timer || true
fi

if [ -f /lib/systemd/system/apt-daily-upgrade.service ] ; then
	systemctl disable apt-daily-upgrade.service || true
	systemctl disable apt-daily-upgrade.timer || true
fi

if [ -f /etc/apt/apt.conf.d/02-no-pdiffs ] ; then
	rm -f /etc/apt/apt.conf.d/02-no-pdiffs || true
fi

if [ -f /etc/apt/apt.conf.d/02-no-languages ] ; then
	rm -f /etc/apt/apt.conf.d/02-no-languages || true
fi

if [ -f /lib/systemd/system/bb-code-server.service ] ; then
	systemctl enable --now bb-code-server.service || true
fi

#DEBHELPER#
