#!/bin/sh

set -e

if [ -f /etc/systemd/timesyncd.conf ] ; then
	sed -i -e 's:#NTP=:NTP=192.168.1.24:g' /etc/systemd/timesyncd.conf
fi

if [ -f /lib/systemd/system/apt-daily.service ] ; then
	systemctl disable apt-daily.service || true
	systemctl disable apt-daily.timer || true
fi

if [ -f /lib/systemd/system/apt-daily-upgrade.service ] ; then
	systemctl disable apt-daily-upgrade.service || true
	systemctl disable apt-daily-upgrade.timer || true
fi

if [ -f /etc/apt/apt.conf.d/02-no-pdiffs ] ; then
	rm -f /etc/apt/apt.conf.d/02-no-pdiffs || true
fi

if [ -f /etc/apt/apt.conf.d/02-no-languages ] ; then
	rm -f /etc/apt/apt.conf.d/02-no-languages || true
fi

if [ -f /usr/lib/systemd/user/code-server.service ] ; then
	if [ -f /etc/systemd/system/multi-user.target.wants/bb-code-server.service ] ; then
		systemctl disable bb-code-server.service || true
	fi

	if [ -d /home/voodoo/ ] ; then
		systemctl enable --now code-server@voodoo || true
		sync ; sleep 1 ; sync
		sed -i -e 's:127.0.0.1:0.0.0.0:g' /home/voodoo/.config/code-server/config.yaml
		sed -i -e 's: password: none:g' /home/voodoo/.config/code-server/config.yaml
		sed -i -e 's:false:true:g' /home/voodoo/.config/code-server/config.yaml
	elif [ -d /home/debian/ ] ; then
		systemctl enable --now code-server@debian || true
		sync ; sleep 1 ; sync
		sed -i -e 's:127.0.0.1:0.0.0.0:g' /home/debian/.config/code-server/config.yaml
		sed -i -e 's: password: none:g' /home/debian/.config/code-server/config.yaml
		sed -i -e 's:false:true:g' /home/debian/.config/code-server/config.yaml
	fi
fi

new_machine=$(cat /proc/device-tree/model | sed "s/ /_/g" | sed "s/-/_/g" | tr -d '\000')
case "${new_machine}" in
BeagleBoard.org_BeagleBone_AI)
	if [ -f /etc/udev/rules.d/81-add-SoftAp0-interface.rules ] ; then
		rm -rf /etc/udev/rules.d/81-add-SoftAp0-interface.rules || true
	fi

	if [ -f /etc/udev/rules.d/82-SoftAp0-start-hostpad.rules ] ; then
		rm -rf /etc/udev/rules.d/82-SoftAp0-start-hostpad.rules || true
	fi

	if [ -f /etc/wpa_supplicant/wpa_supplicant-wlan0.conf ] ; then
		rm -rf /etc/wpa_supplicant/wpa_supplicant-wlan0.conf || true
	fi
	;;
esac

#DEBHELPER#
