#!/bin/sh -e

if ! id | grep -q root; then
	echo "enable-beagle-flasher must be run as root:"
	echo "sudo enable-beagle-flasher"
	exit
fi

if [ -f /etc/default/beagle-flasher ] ; then
	sed -i -e 's:/opt/scripts/tools/eMMC/init-eMMC-flasher-v3.sh:/usr/sbin/init-beagle-flasher:g' /boot/uEnv.txt
	sed -i -e 's:#cmdline=init:cmdline=init:g' /boot/uEnv.txt
	systemctl disable grow_partition.service || true
	echo "log: enable-beagle-flasher"
	echo "log: media is now setup to flash other media"
	echo "log: Shutdown system and this flasher will run on next startup"
else
	echo "log: enable-beagle-flasher"
	echo "log: Please setup /etc/default/beagle-flasher, for the BBB or BBAI..."
	echo "log: #BBB: sudo cp -v /etc/beagle-flasher/beaglebone-black-microsd-to-emmc /etc/default/beagle-flasher"
	echo "log: #BBAI: sudo cp -v /etc/beagle-flasher/bbai-microsd-to-emmc /etc/default/beagle-flasher"
	echo "log: and rerun..."
fi
