#!/bin/sh

set -e

# drop the temporary mask from prerm
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
        systemctl unmask --runtime create_ap.service
        systemctl unmask --runtime create_ap_eth0_bridge.service
fi

#DEBHELPER#

exit 0
