#!/bin/sh

set -e

# drop the temporary mask from prerm
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	systemctl unmask --runtime cmemk-module.service || true
	systemctl unmask --runtime ti-mct-daemon.service || true
fi

#DEBHELPER#

exit 0
