#!/usr/bin/perl
use strict;
use warnings;
use IO::File;
use IO::Pipe;
use feature 'switch';

my $wifi_not_configured = 1;
my $enable_lightdm = 0;
my $enable_ufw = 0;
my $call_reboot = 0;

my ($current_user) = getpwuid(1000);
my ($current_group) = getgrgid(1000);

my ($filename, $conf);

$filename = '/boot/firmware/sysconf.txt';

logger('info', "Reading the system configuration settings from $filename");
$conf = read_conf($filename);

if (my $pass = delete($conf->{root_password})) {
    my $pipe;
    logger('info', 'Resetting root password');
    unless (open($pipe, '|-', '/usr/sbin/chpasswd')) {
	my $err = $!;
	logger('error', "Could not run chpasswd: $err");
	die $err;
    }
    $pipe->print("root:$pass");
    close($pipe);
    $call_reboot = 1;
}

if (my $user_pass = delete($conf->{user_password})) {
    my $pipe;
    logger('info', "Resetting $current_user password");
    unless (open($pipe, '|-', '/usr/sbin/chpasswd')) {
        my $err = $!;
        logger('error', "Could not run chpasswd: $err");
        die $err;
    }
    $pipe->print("$current_user:$user_pass");
    close($pipe);
    if( -f "/etc/issue") {
        system("sed -i -e 's:\\] with a one time password of \\[temppwd\\]:\\]:g' /etc/issue");
    }
    if( -f "/etc/issue.net") {
        system("sed -i -e 's:\\] with a one time password of \\[temppwd\\]:\\]:g' /etc/issue.net");
    }
    $enable_lightdm = 1;
    $call_reboot = 1;
}

if (my $user_enc_pass = delete($conf->{user_encypted_password})) {
    my $pipe;
    logger('info', "Resetting $current_user password");
    unless (open($pipe, '|-', '/usr/sbin/chpasswd', '-e')) {
        my $err = $!;
        logger('error', "Could not run chpasswd: $err");
        die $err;
    }
    $pipe->print("$current_user:$user_enc_pass");
    close($pipe);
    if( -f "/etc/issue") {
        system("sed -i -e 's:\\] with a one time password of \\[temppwd\\]:\\]:g' /etc/issue");
    }
    if( -f "/etc/issue.net") {
        system("sed -i -e 's:\\] with a one time password of \\[temppwd\\]:\\]:g' /etc/issue.net");
    }
    $enable_lightdm = 1;
    $call_reboot = 1;
}

if (my $root_authorized_key = delete($conf->{root_authorized_key})) {
    my $fh;
    logger('info', "Adding key to root's authorized_keys");
    if(! -d "/root/.ssh") {
        if(!mkdir("/root/.ssh", 0700)) {
            my $err = sprintf("Could not create /root/.ssh directory: %s", $!);
            logger('error', $err);
            die $err;
        }
    }

    unless ($fh = IO::File->new('/root/.ssh/authorized_keys', 'w', 0600)) {
        my $err = $!;
        logger('error', "Could not write /root/.ssh/authorized_keys: $err");
        die $err;
    }
    $fh->print($root_authorized_key);
    $fh->close;
}

if (my $user_authorized_key = delete($conf->{user_authorized_key})) {
    my $fh;
    logger('info', "Adding key to $current_user authorized_keys");
    if(! -d "/home/$current_user/.ssh") {
        if(!mkdir("/home/$current_user/.ssh", 0700)) {
            my $err = sprintf("Could not create /home/$current_user/.ssh directory: %s", $!);
            logger('error', $err);
            die $err;
        }
    }

    unless ($fh = IO::File->new("/home/$current_user/.ssh/authorized_keys", 'w', 0600)) {
        my $err = $!;
        logger('error', "Could not write /home/$current_user/.ssh/authorized_keys: $err");
        die $err;
    }
    $fh->print($user_authorized_key);
    $fh->close;

    my $user = 1000;
    my $group = 1000;
    system("chown -R $user:$group /home/$current_user/.ssh/");
}

if (my $new_user_name = delete($conf->{user_name})) {
    logger('info', "Changing $current_user to $new_user_name");
    if ( -f "/etc/systemd/system/default.target.wants/code-server\@$current_user.service") {
        system("systemctl stop code-server\@$current_user.service");
    }
    if( -f "/usr/lib/systemd/system/bb-code-server.service") {
        system("systemctl stop bb-code-server.service");
    }
    system("pkill -u $current_user");
    system("usermod --login $new_user_name --home /home/$new_user_name --move-home $current_user");
    system("groupmod --new-name $new_user_name $current_group");
    if( -f "/etc/issue") {
        system("sed -i -e 's:\\[$current_user\\]:\\[$new_user_name\\]:g' /etc/issue");
    }
    if( -f "/etc/issue.net") {
        system("sed -i -e 's:\\[$current_user\\]:\\[$new_user_name\\]:g' /etc/issue.net");
    }
    if( -f "/etc/lightdm/lightdm.conf") {
        system("sed -i -e 's:autologin-user=$current_user:autologin-user=$new_user_name:g' /etc/lightdm/lightdm.conf");
    }
    if( -f "/etc/lightdm/lightdm.conf.d/$current_user.conf") {
        system("sed -i -e 's:autologin-user=$current_user:autologin-user=$new_user_name:g' /etc/lightdm/lightdm.conf.d/$current_user.conf");
        system("mv /etc/lightdm/lightdm.conf.d/$current_user.conf /etc/lightdm/lightdm.conf.d/$new_user_name.conf");
    }
    if( -f "/home/$new_user_name/.local/share/code-server/coder.json") {
        system("sed -i -e 's:/home/$current_user:/home/$new_user_name:g' /home/$new_user_name/.local/share/code-server/coder.json");
    }
    if ( -f "/etc/systemd/system/default.target.wants/code-server\@$current_user.service") {
        system("systemctl disable code-server\@$current_user.service");
        system("sed -i -e 's:/home/$current_user:/home/$new_user_name:g' /var/www/html/VSCode.html");
        system("systemctl enable code-server\@$new_user_name.service");
    }
    if( -f "/usr/lib/systemd/system/bb-code-server.service") {
        system("sed -i -e 's:User=$current_user:User=$new_user_name:g' /usr/lib/systemd/system/bb-code-server.service");
        system("sed -i -e 's:Group=$current_group:Group=$new_user_name:g' /usr/lib/systemd/system/bb-code-server.service");
        system("sed -i -e 's:/home/$current_user/:/home/$new_user_name/:g' /usr/lib/systemd/system/bb-code-server.service");
    }
    $enable_lightdm = 1;
    $call_reboot = 1;
}

if (my $wifi_regdom = delete($conf->{wifi_regdom})) {
    if( -f "/etc/iwd/main.conf") {
        logger('info', "Setting up iwd with Country code '$wifi_regdom'");
        system("sed -i -e 's:#Country=US:Country=$wifi_regdom:g' /etc/iwd/main.conf");
        if( -f "/boot/firmware/firstrun.sh") {
            logger('info', "Configuring WiFi Credentials");
            system("/usr/lib/beagleboard-sys-mods/iwd_migration.py");
            $wifi_not_configured = 0;
        }
        $call_reboot = 1;
    }
}

if (my $iwd_psk_file = delete($conf->{iwd_psk_file})) {
    if ($wifi_not_configured) {
        if( -f "/boot/firmware/services/$iwd_psk_file") {
            logger('info', "Setting up iwd with '$iwd_psk_file'");
            system("cp /boot/firmware/services/$iwd_psk_file /var/lib/iwd/");
            system("dos2unix -q /var/lib/iwd/$iwd_psk_file");
            $wifi_not_configured = 0;
            $call_reboot = 1;
        }
    }
}

if (my $iwd_psk_file_contents = delete($conf->{iwd_psk_file_contents})) {
    logger('info', "Obsolete iwd_psk_file_contents");
}

if (my $hostapd_file = delete($conf->{hostapd_file})) {
    if( -f "/boot/firmware/services/$hostapd_file") {
        logger('info', "Setting up hostapd with '$hostapd_file'");
        system("cp /boot/firmware/services/$hostapd_file /etc/hostapd/SoftAp0.conf");
        system("dos2unix -q /etc/hostapd/SoftAp0.conf");
        $call_reboot = 1;
    }
}

if (my $name = delete($conf->{hostname})) {
    my $fh;
    logger('info', "Setting hostname to '$name'");
    unless ($fh = IO::File->new('/etc/hostname', 'w')) {
	my $err = $!;
	logger('error', "Could not write hostname '$name': $err");
	die $err;
    }
    $fh->print($name);
    $fh->close;
    system('hostname', '--file', '/etc/hostname');

    my $fha;
    logger('info', "Adding '$name' to /etc/hosts");
    unless ($fha = IO::File->new('/etc/hosts', 'w')) {
	my $err = $!;
	logger('error', "Could not write to /etc/hosts '$name': $err");
	die $err;
    }
    $fha->print("127.0.0.1	localhost\n");
    $fha->print("127.0.1.1	", $name, ".localdomain	", $name, "\n");
    $fha->print("\n");
    $fha->print("# The following lines are desirable for IPv6 capable hosts\n");
    $fha->print("::1		localhost ip6-localhost ip6-loopback\n");
    $fha->print("ff02::1		ip6-allnodes\n");
    $fha->print("ff02::2		ip6-allrouters\n");
    $fha->close;
    $call_reboot = 1;
}

if (my $new_keymap = delete($conf->{keymap})) {
    logger('info', "Setting keymap to '$new_keymap'");
    system("/usr/lib/beagleboard-sys-mods/imager_custom set_keymap '$new_keymap'");
    $call_reboot = 1;
}

if (my $new_timezone = delete($conf->{timezone})) {
    logger('info', "Setting timezone to '$new_timezone'");
    system("/usr/lib/beagleboard-sys-mods/imager_custom set_timezone '$new_timezone'");
    $call_reboot = 1;
}

if (my $legacy_rndis_support = delete($conf->{legacy_rndis_support})) {
    if( -f "/etc/default/bb-boot") {
        logger('info', "Enabling Legacy RNDIS support");
        system("sed -i -e 's:USB_RNDIS_DISABLED=yes:#USB_RNDIS_DISABLED=yes:g' /etc/default/bb-boot");
        $call_reboot = 1;
    }
}

if (my $new_enable_ufw = delete($conf->{enable_ufw})) {
    logger('info', "UFW: Enable UFW firewall");
    $enable_ufw = 1;
}

if (my $new_ufw_allow_ssh = delete($conf->{ufw_allow_ssh})) {
    logger('info', "UFW: allow ssh access over port 22");
    system("ufw allow 22");
    $enable_ufw = 1;
}

if (my $new_ufw_allow_http = delete($conf->{ufw_allow_http})) {
    logger('info', "UFW: allow http access over port 80");
    system("ufw allow 80");
    $enable_ufw = 1;
}

if (my $new_ufw_allow_https = delete($conf->{ufw_allow_https})) {
    logger('info', "UFW: allow https access over port 443");
    system("ufw allow 443");
    $enable_ufw = 1;
}

if (my $new_ufw_allow_nodered = delete($conf->{ufw_allow_nodered})) {
    logger('info', "UFW: allow nodered access over port 1880");
    system("ufw allow 1880");
    $enable_ufw = 1;
}

if (my $new_ufw_allow_vscode = delete($conf->{ufw_allow_vscode})) {
    logger('info', "UFW: allow vscode access over port 3000");
    system("ufw allow 3000");
    $enable_ufw = 1;
}

if (my $new_ufw_allow_vnc = delete($conf->{ufw_allow_vnc})) {
    logger('info', "UFW: allow vnc access over port 5901");
    system("ufw allow 5901");
    $enable_ufw = 1;
}

if (my $new_ufw_allow_cockpit = delete($conf->{ufw_allow_cockpit})) {
    logger('info', "UFW: allow cockpit access over port 9090");
    system("ufw allow 9090");
    $enable_ufw = 1;
}

rewrite_conf_file($filename, $conf);

if ($enable_ufw) {
    logger('info', "UFW: Enabling UFW firewall");
    system("ufw enable");
    system("ufw status");
    $call_reboot = 1;
}

if ($enable_lightdm) {
    if( -f "/usr/lib/systemd/system/lightdm.service") {
        logger('info', "Enabling lightdm.service");
        system("systemctl enable lightdm.service");
    }
}

if ($call_reboot) {
    logger('info', "**********************************************");
    logger('info', "Rebooting after setting up sysconf.txt options");
    logger('info', "**********************************************");
    sleep 2;
    system('systemctl', '--message="Rebooting after setting up sysconf.txt options"', 'reboot');
}

exit 0;

sub read_conf {
    my ($file, $conf, $fh);
    $file = shift;

    $conf = {};
    unless ($fh = IO::File->new($filename, 'r')) {
	my $err = $!;
	logger('error', "Could not read from configuration file '$filename': $err");
	# Not finding the config file is not fatal: there is just
	# nothing to configure!
	return $conf;
    }
    while (my $line = $fh->getline) {
	my ($key, $value);
	# Allow for comments, and properly ignore them
	$line =~ s/#.+//;
	if ( ($key, $value) = ($line =~ m/^\s*([^=]+)\s*=\s*(.*)\s*$/)) {
	    $key = lc($key);
	    if (exists($conf->{$key})) {
		logger('warn',
		       "Repeated configuration key: $key. " .
		       "Overwriting with new value ($value)");
	    }
	    $conf->{$key} = $value;
	}
    }
    $fh->close;

    return $conf;
}

sub logger {
    my ($prio, $msg) = @_;
    system('logger', '-p', "daemon.$prio", '-t', 'bbbio-set-sysconf', $msg);
    system('echo', $msg);
}

sub rewrite_conf_file {
    my ($filename, $conf) = @_;
    my $fh;
    unless ($fh = IO::File->new($filename, 'w')) {
	my $err = $!;
	logger('error', "Could not write to configuration file '$filename': $err");
	die $err;
    }
    $fh->print(
q(# This file will be automatically evaluated and installed at next boot
# time, and regenerated (to avoid leaking passwords and such information).
#
# To force it to be evaluated immediately, you can run (as root):
#
#     /usr/sbin/bbbio-set-sysconf
#
# You can disable the file evaluation by disabling the bbbio-set-sysconf
# service in systemd:
#
#     systemctl disable bbbio-set-sysconf
#
# Comments (all portions of a line following a '#' character) are
# ignored. This file is read line by line. Valid
# configuration lines are of the form 'key=value'. Whitespace around
# 'key' and 'value' is ignored. This file will be _regenerated_ every
# time it is evaluated.
#
# We follow the convention to indent with one space comments, and
# leave no space to indicate the line is an example that could be
# uncommented.

# root_password - Set a password for the root user (not used in ubuntu)
#root_password=FooBar

# root_authorized_key - Set an authorized key for a root ssh login (not used in ubuntu)
#root_authorized_key=

# user_name - Set a user name for the user (1000)
#user_name=beagle

# user_password - Set a password for user (1000)
#user_password=FooBar

# user_authorized_key - Set an authorized key for a user (1000) ssh login
#user_authorized_key=

# iwd_psk_file - Set a configuration for iwd https://wiki.archlinux.org/title/iwd
#iwd_psk_file=

# wifi_regdom - Country Code (ISO Alpha-2) Requests the country be set for the system.
#wifi_regdom=US

# hostapd_file - Set a configuration for hostapd https://wiki.gentoo.org/wiki/Hostapd
#hostapd_file=SoftAp0.conf

# hostname - Set the system hostname.
#hostname=BeagleBone

# keymap - Set the system keymap.
#keymap=us

# timezone - Set the system timezone.
#timezone=America/Chicago

# enable_ufw - enable ufw firewall (https://en.wikipedia.org/wiki/Uncomplicated_Firewall)
#enable_ufw=yes

# ufw_allow_ssh - allow ssh access over port 22
#ufw_allow_ssh=yes

# ufw_allow_http - allow http access over port 80
#ufw_allow_http=yes

# ufw_allow_https - allow https access over port 443
#ufw_allow_https=yes

# ufw_allow_nodered - allow nodered access over port 1880 (https://nodered.org/)
#ufw_allow_nodered=yes

# ufw_allow_vscode - allow vscode access over port 3000 (https://github.com/coder/code-server)
#ufw_allow_vscode=yes

# ufw_allow_vnc - allow vnc access over port 5901
#ufw_allow_vnc=yes

# ufw_allow_cockpit - allow cockpit access over port 9090 (https://cockpit-project.org/)
#ufw_allow_cockpit=yes
));

    if (scalar keys %$conf) {
	logger('warn', 'Unprocessed keys left in /boot/firmware/sysconf.txt: ' .
	       join(', ', sort keys %$conf));
	$fh->print(
q(
# We found the following unhandled keys - That means, the
# configuration script does not know how to handle them. Please
# double-check them!
));
	$fh->print(join('', map {sprintf("%s=%s\n", $_, $conf->{$_})} sort keys %$conf));
    }
    $fh->close;
}

