.TH ASSIMP "1" "August 2011" "assimp 2.0.863" "assimp"
.SH NAME
assimp \- Open Asset Import Library Tool
.SH SYNOPSIS
.B assimp 
 <arguments>
.SH DESCRIPTION
assimp: is a command line utilitiy that allows interaction with 3D models
.SH VERBS
.IP
Use 'assimp <verb> \fB\-\-help\fR' to get detailed help for a command.
.TP
info
Display statistics and structure of a 3D model
.TP
version
Display Assimp version
.TP
listext
List all known file extension
.TP
knowext
Check whether a file extension is recognized by Assimp
.TP
extract
Extract an embedded texture from a model
.TP
dump
Convert a model to binary or XML dumps (ASSBIN/ASSXML)
.TP
cmpdump
Compare two file dumps produced with 'assimp dump <file> \fB\-s\fR ...'
.SH MANUAL
On Debian systems you should be able to find a manual in
.B file:///usr/share/doc/assimp-utils/assimp/index.html
