#!/bin/sh

[ -e debian/tests.home ] || mkdir debian/tests.home
export HOME="$(pwd)/debian/tests.home"
mkdir "$HOME"/.config || true
xvfb-run -a --server-args="-screen 0 1024x768x24" \
    Xephyr -reset -br -screen 1024x768 :2 & x_pid=$!

trap "kill ${x_pid}; rm -rf debian/tests.home" EXIT

DISPLAY=:2 dbus-launch --exit-with-session debian/tests/testsuite.xsession
