.TH "qterminal" 1
.SH NAME
qterminal \- simple terminal in qt 
.SH SYNOPSIS
.B qterminal
[OPTIONS]

.SH DESCRIPTION

.B qterminal
is a simple terminal in qt, without KDE dependancies.

.SH OPTIONS
.TP
.B \-h, \-\-help
Print this help.
.TP
.B \-v, \-\-version
Prints application version and exits.
.TP
.B \-w, \-\-workdir <dir>
Start session with specified work directory.
.TP
.B \-e, \-\-execute <dir>
Execute command instead of shell.
.TP
.B \-d, \-\-drop <dir>
Start in Drop Mode, like Yakuake or Tilda.

.SH AUTHORS
Petr Vanek <petr@scribus.info>

Maxim Bourmitrov <maxim.bourmistrov@unixconn.com>

Vladimir Kuznetsov <vovanec@gmail.com>

Man page written to conform with Debian by Julien Lavergne.
