#!/bin/sh

if ! id | grep -q root; then
	echo "must be run as root"
	exit
fi

log="bb-install-modules:"

. /opt/modules/install

case "${ARCH_SOC_MODULES}" in
am335x)
	dpkg -i /opt/modules/ti-sgx-ti335x-modules-${uname}_armhf.deb || true
	dpkg -i /opt/modules/bbb.io-kernel-${branch}-am335x*.deb || true
	dpkg -i /opt/modules/bbb.io-kernel-${branch}*.deb || true
	;;
am57xx)
	dpkg -i /opt/modules/ti-sgx-jacinto6evm-modules-${uname}_armhf.deb || true
	dpkg -i /opt/modules/bbb.io-kernel-${branch}-am57xx*.deb || true
	dpkg -i /opt/modules/bbb.io-kernel-${branch}*.deb || true
	;;
*)
	echo "Please update ARCH_SOC_MODULES in /etc/default/generic-sys-mods"
	;;
esac
