.TH DTC 1 "30 January 2012" "Linux"
.SH NAME
\fBfdtput\fP \- write a property value to a device-tree
.SH SYNOPSIS
\fB/usr/bin/fdtput\fP <options> <dt file> <<node> <property> [<value>...]
.SH DESCRIPTION
Write a property value to a device-tree. The command line arguments are
joined together into a single value.
.SH OPTIONS
.TP
\fB\-h\fR
Print this help.
.TP
\fB\-v\fR
Verbose: display each value decoded from command line
.TP
\fB\-t\fR <type>
Type of data
.IP
<type>  s=string, i=int, u=unsigned, x=hex
.br
Optional modifier prefix:
.br
hh or b=byte, h=2 byte, l=4 byte (default)
.SH AUTHOR
\fBfdtput\fP was written by The Chromium OS Authors.
.PP
This manual page was written by H\['e]ctor Or\['o]n
<zumbi@debian.org>, for the Debian project (but may be used by others).
