#!/bin/sh

set -e

if [ ! -f /etc/ssl/certs/gitlab.gfnd.rcn-ee.org.crt ] ; then
	wget --quiet --directory-prefix=/tmp/ http://192.168.1.98/mirror/internal/gitlab.gfnd.rcn-ee.org.crt
	sync
	cp -v /tmp/gitlab.gfnd.rcn-ee.org.crt /etc/ssl/certs/
fi
chmod 644 /etc/ssl/certs/gitlab.gfnd.rcn-ee.org.crt

if [ ! -f /etc/ssl/certs/git.gfnd.rcn-ee.org.crt ] ; then
	wget --quiet --directory-prefix=/tmp/ http://192.168.1.98/mirror/internal/git.gfnd.rcn-ee.org.crt
	sync
	cp -v /tmp/git.gfnd.rcn-ee.org.crt /etc/ssl/certs/
fi
chmod 644 /etc/ssl/certs/git.gfnd.rcn-ee.org.crt

if [ -f /etc/systemd/timesyncd.conf ] ; then
	sed -i -e 's:#NTP=:NTP=192.168.1.12:g' /etc/systemd/timesyncd.conf

	timedatectl set-timezone America/North_Dakota/Center
	timedatectl set-ntp true
	timedatectl
fi

if [ -f /etc/apt/apt.conf.d/02-no-pdiffs ] ; then
	rm -f /etc/apt/apt.conf.d/02-no-pdiffs || true
fi

if [ -f /etc/apt/apt.conf.d/02-no-languages ] ; then
	rm -f /etc/apt/apt.conf.d/02-no-languages || true
fi

if [ -f /etc/apt/apt.conf.d/80proxy ] ; then
	rm -f /etc/apt/apt.conf.d/80proxy || true
fi

if [ ! -f /etc/modules-load.d/spidev.conf ] ; then
	echo "spidev" > /etc/modules-load.d/spidev.conf
fi

if [ ! -d /mnt/farm/uptime/ ] ; then
	mkdir -p /mnt/farm || true
	echo "192.168.1.89:/mnt/tank/farm /mnt/farm nfs defaults" >> /etc/fstab

	CURRENT_USER=$(id -nu 1000)
	chown -R ${CURRENT_USER}:${CURRENT_USER} /mnt/farm || true
fi

if [ -f /lib/systemd/system/beagle-flasher-init-shutdown.service ] ; then
	systemctl disable beagle-flasher-init-shutdown.service || true
fi

new_machine=$(cat /proc/device-tree/model | sed "s/ /_/g" | sed "s/-/_/g" | tr -d '\000')
case "${new_machine}" in
BeagleBoard.org_BeagleBone_AI)
	if [ -f /etc/udev/rules.d/81-add-SoftAp0-interface.rules ] ; then
		rm -rf /etc/udev/rules.d/81-add-SoftAp0-interface.rules || true
	fi

	if [ -f /etc/udev/rules.d/82-SoftAp0-start-hostpad.rules ] ; then
		rm -rf /etc/udev/rules.d/82-SoftAp0-start-hostpad.rules || true
	fi

	if [ -f /etc/wpa_supplicant/wpa_supplicant-wlan0.conf ] ; then
		rm -rf /etc/wpa_supplicant/wpa_supplicant-wlan0.conf || true
	fi
	;;
esac

CURRENT_USER=$(id -nu 1000)
echo "${CURRENT_USER}    ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/${CURRENT_USER}

#DEBHELPER#
