#!/bin/sh

set -e

if [ ! -f /etc/ssl/certs/gitlab.gfnd.rcn-ee.org.crt ] ; then
	wget --quiet --directory-prefix=/tmp/ http://192.168.1.98/internal/gitlab.gfnd.rcn-ee.org.crt
	sync
	cp -v /tmp/gitlab.gfnd.rcn-ee.org.crt /etc/ssl/certs/
fi

if [ -f /etc/systemd/timesyncd.conf ] ; then
	sed -i -e 's:#NTP=:NTP=192.168.1.12:g' /etc/systemd/timesyncd.conf
	sed -i -e 's:NTP=192.168.1.24:NTP=192.168.1.12:g' /etc/systemd/timesyncd.conf

	timedatectl
	timedatectl set-timezone America/North_Dakota/Center
	timedatectl set-ntp true
	timedatectl
fi

if [ -f /lib/systemd/system/apt-daily.service ] ; then
	systemctl disable apt-daily.service || true
	systemctl disable apt-daily.timer || true
fi

if [ -f /lib/systemd/system/apt-daily-upgrade.service ] ; then
	systemctl disable apt-daily-upgrade.service || true
	systemctl disable apt-daily-upgrade.timer || true
fi

if [ -f /etc/apt/apt.conf.d/02-no-pdiffs ] ; then
	rm -f /etc/apt/apt.conf.d/02-no-pdiffs || true
fi

if [ -f /etc/apt/apt.conf.d/02-no-languages ] ; then
	rm -f /etc/apt/apt.conf.d/02-no-languages || true
fi

if [ ! -d /mnt/farm/uptime/ ] ; then
	mkdir -p /mnt/farm || true
	echo "192.168.1.3:/var/www/html/farm /mnt/farm nfs defaults" >> /etc/fstab

	if [ -d /home/voodoo/ ] ; then
		chown -R voodoo:voodoo /mnt/farm
	elif [ -d /home/debian/ ] ; then
		chown -R debian:debian /mnt/farm
	elif [ -d /home/ubuntu/ ] ; then
		chown -R ubuntu:ubuntu /mnt/farm
	elif [ -d /home/beagle/ ] ; then
		chown -R beagle:beagle /mnt/farm
	fi
fi

if [ -f /lib/systemd/system/beagle-flasher-init-shutdown.service ] ; then
	systemctl disable beagle-flasher-init-shutdown.service || true
fi

if [ -f /usr/lib/systemd/user/code-server.service ] ; then
	if [ -f /etc/systemd/system/multi-user.target.wants/bb-code-server.service ] ; then
		systemctl disable bb-code-server.service || true
	fi

	soc_family=$(cat /sys/devices/soc0/family || true)

	case "${soc_family}" in
	DRA7)
		if [ -d /home/voodoo/ ] ; then
			systemctl enable code-server@voodoo || true
			mkdir -p  /home/voodoo/.config/code-server/ || true
			echo "bind-addr: 0.0.0.0:8080" > /home/voodoo/.config/code-server/config.yaml
			echo "auth: none" >> /home/voodoo/.config/code-server/config.yaml
			echo "cert: true" >> /home/voodoo/.config/code-server/config.yaml
			chown -R voodoo:voodoo /home/voodoo/.config/
		elif [ -d /home/debian/ ] ; then
			systemctl enable --now code-server@debian || true
			mkdir -p  /home/debian/.config/code-server/ || true
			echo "bind-addr: 0.0.0.0:8080" > /home/debian/.config/code-server/config.yaml
			echo "auth: none" >> /home/debian/.config/code-server/config.yaml
			echo "cert: true" >> /home/debian/.config/code-server/config.yaml
			chown -R debian:debian /home/debian/.config/
		fi
		;;
	esac
fi

new_machine=$(cat /proc/device-tree/model | sed "s/ /_/g" | sed "s/-/_/g" | tr -d '\000')
case "${new_machine}" in
BeagleBoard.org_BeagleBone_AI)
	if [ -f /etc/udev/rules.d/81-add-SoftAp0-interface.rules ] ; then
		rm -rf /etc/udev/rules.d/81-add-SoftAp0-interface.rules || true
	fi

	if [ -f /etc/udev/rules.d/82-SoftAp0-start-hostpad.rules ] ; then
		rm -rf /etc/udev/rules.d/82-SoftAp0-start-hostpad.rules || true
	fi

	if [ -f /etc/wpa_supplicant/wpa_supplicant-wlan0.conf ] ; then
		rm -rf /etc/wpa_supplicant/wpa_supplicant-wlan0.conf || true
	fi
	;;
esac

if [ -d /home/voodoo/ ] ; then
	echo "voodoo    ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/voodoo
elif [ -d /home/debian/ ] ; then
	echo "debian    ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/debian
elif [ -d /home/ubuntu/ ] ; then
	echo "ubuntu    ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/ubuntu
elif [ -d /home/beagle/ ] ; then
	echo "beagle    ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/beagle
fi

#DEBHELPER#
