#!/bin/sh

set -e

case "${1}" in
    purge)
        # remove cache files if no other gio module is left
        if ! ls /usr/lib/gio/modules/*.so > /dev/null 2>&1
            then
            rm -f /usr/lib/gio/modules/giomodule.cache
        fi
    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`${1}'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
