.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH IS_AUFS 1 "March 21, 2009"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
is_aufs \- program to check whether a filesystem is an aufs filesystem
.SH SYNOPSIS
.B is_aufs
.RI "\fIMOUNTPOINT\fR"
.SH DESCRIPTION
This manual page documents briefly the
.B is_aufs
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBis_aufs\fP is a program that checks whether a filesystem (mountpoint)
is aufs.
.SH OPTIONS
Pass the mountpoint as the parameter
.SH SEE ALSO
.BR aufs (5),
.br
.SH AUTHOR
is_aufs was written by Stefanos Harhalakis <v13@v13.gr>
.PP
This manual page was written by Stefanos Harhalakis <v13@v13.gr>,
for the Debian project (but may be used by others).
