#!/bin/sh -e

case "$1" in
  purge | remove)
  [ ! -L /etc/udev/rules.d/xenomai.rules ] || rm /etc/udev/rules.d/xenomai.rules
  ;;
esac

# Automatically added by dh_installinit/13.3.4
if [ "$1" = "purge" ] ; then
	update-rc.d xenomai remove >/dev/null
fi
# End automatically added section

