#!/bin/sh -e

case "$1" in
    configure)
        # Add the xenomai group unless it's already there
        if ! getent group xenomai >/dev/null; then
            addgroup --quiet --system xenomai || true
        fi
        rm -f /etc/udev/rules.d/xenomai.rules
        ln -sf ../xenomai.rules /etc/udev/rules.d/xenomai.rules
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_installinit/13.3.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/xenomai" ]; then
		update-rc.d xenomai defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d xenomai $_dh_action || exit 1
	fi
fi
# End automatically added section

