#!/bin/sh

set -e

if [ ! -f /etc/systemd/system/getty.target.wants/serial-getty@ttyGS0.service ] ; then
	systemctl enable serial-getty@ttyGS0.service
fi

if [ ! -f /etc/systemd/network/usb0.network ] ; then
	cp -v /etc/bbb.io/templates/usb0-DHCPServer.network /etc/systemd/network/usb0.network
fi

if [ ! -f /etc/systemd/network/usb1.network ] ; then
	cp -v /etc/bbb.io/templates/usb1-DHCPServer.network /etc/systemd/network/usb1.network
fi

#DEBHELPER#
