usr/bin/dm-tool
usr/sbin/lightdm
usr/share/man
usr/share/locale
usr/share/help
etc/apparmor.d/abstractions/lightdm
etc/apparmor.d/abstractions/lightdm_chromium-browser
etc/dbus-1
etc/lightdm/users.conf
etc/lightdm/lightdm.conf
etc/lightdm/keys.conf
etc/apparmor.d/lightdm-guest-session
etc/pam.d
debian/lightdm-xsession.desktop /usr/share/xsessions
debian/01_debian.conf /usr/share/lightdm/lightdm.conf.d
usr/lib/*/lightdm/lightdm-guest-session
