.TH connmand 8 "3 February 2010" "" "connmand Manual"

.SH NAME
connmand \- connection manager

.SH SYNOPSIS
.B connmand
.RI [ options ]
.br

.SH DESCRIPTION
This manual page explains the \fBconnmand\fP daemon. \fBconnmand\fP is used to manage internet connections on embedded devices.

.SH OPTIONS
.IP \fB\-h/\-\-help\fP
Shows help options and usage information.

.IP \fB\-d/\-\-debug=DEBUG\fP
Specify debug options to enable.

.IP \fB\-i/\-\-device=DEV\fP
Specify a networking device or interface to manage.

.IP \fB\-I/\-\-nodevice=DEV\fP
Specify a networking device or interface to ignore.

.IP \fB\-p/\-\-plugin=NAME\fP
Specify a plugin that should be loaded.

.IP \fB\-P/\-\-noplugin=NAME\fP
Specify a plugin that should be excluded from loading.

.IP \fB\-W/\-\-wifi=NAME\fP
Specify a driver to use for WiFi/Supplicant.

.IP \fB\-n/\-\-nodaemon\fP
Do not fork to background.

.IP \fB\-c/\-\-compat\fP
Enable compatibility with NetworkManager.

.IP \fB\-t/\-\-selftest\fP
Run self-testing routines.

.IP \fB\-v/\-\-version\fP
Show version information and exit.

.SH AUTHOR

Mathieu Trudel <mathieu\-tl@ubuntu.com>

