#!/bin/bash

if ! id | grep -q root; then
	echo "beagleconnect-start-gateway must be run as root:"
	echo "sudo beagleconnect-start-gateway"
	exit
fi

rm -rf /var/log/gbridge.log

IEEE_802154_CHANNEL=26
if [[ $(iwpan phy | grep -c "906 MHz") -ne "0" ]]; 
then
  IEEE_802154_CHANNEL=1
  echo "setting up wpanusb gateway for IEEE 802154 CHANNEL 1(906 Mhz)"
else
  echo "setting up wpanusb gateway for IEEE 802154 CHANNEL 26"
fi

IFLP=`ifconfig | grep lowpan`

###FIXME: Convert this to a udev rule...
ip link set wpan0 down
iwpan phy phy0 set channel 0 $IEEE_802154_CHANNEL
iwpan dev wpan0 set pan_id 0xabcd
ip link add link wpan0 name lowpan0 type lowpan
ip link set lowpan0 up
ip link set wpan0 up
ip -6 addr add 2001:db8::2/64 dev lowpan0
sleep 1

ping6 -I lowpan0 2001:db8::1 -c 5
sleep 1

###FIXME: Need to convert this to a systemd service..
gbridge > /var/log/gbride.log 2>&1 &
sleep 5

keep_alive () {
  while true; do gpioset 4 18=1; gpioset 4 18=0; sleep 1; done
}

keep_alive > /dev/null 2>&1 &
