.TH DTC 1 "30 January 2012" "Linux"
.SH NAME
\fBfdtdump\fP \- prints a readable version of a flat device-tree file.
.SH SYNOPSIS
\fB/usr/bin/fdtdump\fP <DTB-file-name>
.SH DESCRIPTION
The fdtdump program prints a readable version of a flat device-tree file.
.SH AUTHOR
\fBfdtdump\fP was written by Pantelis Antoniou
<pantelis.antoniou AT gmail.com>.
.PP
This manual page was written by H\['e]ctor Or\['o]n
<zumbi@debian.org>, for the Debian project (but may be used by others).
