#!/bin/sh
set -e

if [ "$1" = configure ]; then
    adduser --quiet --system --group --no-create-home --home /run/systemd \
        --gecos "systemd core dump processing" systemd-coredump

    # enable systemd-coredump right after package installation
    if [ -d /run/systemd/system ]; then
        systemctl daemon-reload && systemctl start systemd-coredump.socket || true
    fi
    /lib/systemd/systemd-sysctl /usr/lib/sysctl.d/50-coredump.conf || true
fi

#DEBHELPER#
