.TH CATKIN-PKG 1

.SH NAME

catkin_find_pkg \- find a catkin package

.SH SYNOPSIS

.B catkin_find_pkg [-h] pkg [base_path]

.SH DESCRIPTION

Script to find catkin packages.

.SH OPTIONS

.TP 5
\-h, \-\-help
show this help message and exit

.TP 5
[pkg]
Name of the pkg to find.

.TP 5
[base_path]
Base path to crawl for packages

.SH AUTHOR

Willow Garage and the Open Source Robotics Foundation.
