.TH CATKIN-PKG 1

.SH NAME

catkin_test_changelog \- test a REP-0132 CHANGELOG.rst

.SH SYNOPSIS

.B catkin_test_changelog [-h] [changelog_file]

.SH DESCRIPTION

Test a REP-0132 CHANGELOG.rst

.SH OPTIONS

.TP 5
\-h, \-\-help
show this help message and exit

.SH AUTHOR

Willow Garage and the Open Source Robotics Foundation.
