.TH CATKIN-PKG 1

.SH NAME

catkin_generate_changelog \- generate a REP-0132 CHANGELOG.rst

.SH SYNOPSIS

.B catkin_generate_changelog [-h] [-a] [--print-root] [-y]

.SH DESCRIPTION

Generate a REP-0132 CHANGELOG.rst

.SH OPTIONS

.TP 5
\-h, \-\-help
show this help message and exit

.TP 5
\-a, \-\-all
Generate changelog for all versions instead of only
the forthcoming one (only supported when no changelog
file exists yet)

.TP 5
\-\-print\-root
Output changelog content to the console as if there
would be only one package in the root of the repository

\-y, \-\-non\-interactive
Run without user interaction, confirming all questions with 'yes'

.SH AUTHOR

Willow Garage and the Open Source Robotics Foundation.
