.TH CATKIN-PKG 1

.SH NAME

catkin_tag_changelog \- tag changelog forthcoming section with upcoming version

.SH SYNOPSIS

.B catkin_tag_changelog [-h] [--bump {major,minor,patch}]

.SH DESCRIPTION

Tag the forthcoming section in the changelog files with an upcoming version
number.

.SH OPTIONS

.TP 5
\-h, \-\-help
show this help message and exit

.TP 5
\-\-bump {major,minor,patch}
Which part of the version number to bump? (default: patch)


.SH AUTHOR

Willow Garage and the Open Source Robotics Foundation.
