.TH CATKIN-PKG 1

.SH NAME

catkin_create_pkg \- create a new catkin package

.SH SYNOPSIS

.B catkin_create_pkg [OPTIONS] name [dependencies [dependencies ...]]

.SH DESCRIPTION

Create a new catkin package.

.SH OPTIONS

.TP 5
\-h, \-\-help
show this help message and exit

.TP 5
\-s [SYS_DEPS [SYS_DEPS ...]], \-\-sys\-deps [SYS_DEPS [SYS_DEPS ...]]
System Dependencies

.TP 5
\-b [BOOST_COMPS [BOOST_COMPS ...]], \-\-boost\-comps [BOOST_COMPS [BOOST_COMPS ...]]
Boost Components

.TP 5
\-V PKG_VERSION, \-\-pkg_version PKG_VERSION
Initial Package version

.TP 5
\-D DESCRIPTION, \-\-description DESCRIPTION
Description

.TP 5
\-l LICENSE, \-\-license LICENSE
Name for License, (e.g. BSD, MIT, GPLv3...)

.TP 5
\-a AUTHOR, \-\-author AUTHOR
A single author, may be used multiple times

.TP 5
\-m MAINTAINER, \-\-maintainer MAINTAINER
A single maintainer, may be used multiple times

.SH AUTHOR

Willow Garage and the Open Source Robotics Foundation.
