.TH DTC 1 "30 January 2012" "Linux"
.SH NAME
\fBconvert-dtsv0\fP \- Device Tree Compiler -- Conversion to Version 1
.SH SYNOPSIS
\fB/usr/bin/convert-dtsv0\fP [<input_filename ... >]
.SH DESCRIPTION
convert-dtsv0 is a small utility program which converts (DTS)

Device Tree Source from the obsolete version 0 to version 1.
Version 1 DTS files are marked by line "/dts-v1/;" at the top of the file.

Each file passed will be converted to the new /dts-v1/ version by creating
a new file with a "v1" appended the filename.

Comments, empty lines, etc. are preserved.
.SH AUTHOR
\fBconvert-dtsv0\fP was written by David Gibson
<david@gibson.dropbear.id.au>. Since April 1, 2006, Jon Loeliger
<jdl@jdl.com> assumes maintainership.
.PP
This manual page was written by H\['e]ctor Or\['o]n
<zumbi@debian.org>, for the Debian project (but may be used by others).
