#!/bin/sh

set -e

# drop the temporary mask from prerm
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	systemctl unmask --runtime wifidog-gateway.service || true
	systemctl unmask --runtime wificonfig.service || true
fi

#DEBHELPER#

exit 0
