#!/bin/bash -e

if [ ! -f /tmp/wifi.up ] ; then
	iw dev SoftAp0 del &> /dev/null || true

	iw phy phy0 interface add SoftAp0 type managed

	p=$?
	if [ $p==0 ];then
		echo "phy0 created "
	else
		echo "Err: can't creat phy0 "
		exit 1
	fi

	ip link set dev SoftAp0 down
	ip link set dev SoftAp0 address 02:03:04:05:06:07
	ip link set dev SoftAp0 up
	ip addr add 192.168.8.1/24 broadcast 192.168.8.255 dev SoftAp0

	echo 1 > /proc/sys/net/ipv4/ip_forward
	iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE
	iptables -A FORWARD -i wlan0 -o SoftAp0 -m state --state RELATED,ESTABLISHED -j ACCEPT
	iptables -A FORWARD -i SoftAp0 -o wlan0 -j ACCEPT
	touch /tmp/wifi.up
fi

#FIXME: (little racy, but this works, "/usr/bin/wifidog -f -d 7" needs to go into it's own service file...)
systemctl start wificonfig.service || true

/usr/bin/wifidog -f -d 7
#systemctl start wificonfig.service || true
