.TH es2_info 1 "2011-02-01"
.SH NAME
es2_info \- list OpenGL ES extensions
.SH SYNOPSIS
.B es2_info
.RI [ options ]
.SH DESCRIPTION
The \fIes2_info\fP program shows information about the supported OpenGL ES
extensions.
.SH OPTIONS
.TP 8
.B \-display \fIdisplay\fP
Specify the X display to run on.
.TP 8
.B \-h
Print usage information.
.SH AUTHOR
es2_info was written by Tungsten Graphics.
.PP
This manual page was written by Ricardo Salveti de Araujo <ricardo.salveti@canonical.com>,
for the Debian project (but may be used by others).
