.TH es2gears 1 "2011-02-01"
.SH NAME
es2gears \- ``gears'' demo for GLES2
.SH SYNOPSIS
.B es2gears
.SH DESCRIPTION
The \fIes2gears\fP program is a port of the ``gears'' demo to GLES2. It displays
a set of rotating gears and prints out the frame rate at regular intervals. It
has become quite popular as basic benchmarking tool.
.SH AUTHOR
glxgears was written by Brian Paul <brian.paul@tungstengraphics.com>.
.PP
This manual page was written by Ricardo Salveti de Araujo <ricardo.salveti@canonical.com>,
for the Debian project (but may be used by others).
