.TH es2tri 1 "2011-02-01"
.SH NAME
es2tri \- a draw demonstration using X/EGL and OpenGL ES 2.x
.SH SYNOPSIS
.B es2tri
.SH DESCRIPTION
The \fIes2tri\fP program demonstrate the usage of X/EGL and OpenGL ES 2.x by
drawing a triangle at the screen. This program is most useful when studied
in its source code form.
.SH AUTHOR
es2tri was written by Tungsten Graphics.
.PP
This manual page was written by Ricardo Salveti de Araujo <ricardo.salveti@canonical.com>,
for the Debian project (but may be used by others).
