#!/usr/bin/python3

import subprocess
import time
import sys

import server
import chromedriver

cd_server = server.Server('/usr/lib/chromium-browser/chromedriver2_server')
driver = chromedriver.ChromeDriver(cd_server.GetUrl())
driver.Load('http://www.google.com')
driver.Quit()
cd_server.Kill()

