#!/bin/bash

# A thin wrapper that sets up an environment, runs a test, and exits with an
# error if the test does not write a file indicating success.
# Copyright Canonical, 2013.   Author: Chad MILLER <chad.miller@canonical.com>

set -o nounset

SRCDIR=$(pwd)
WORKDIR=$(mktemp -d --tmpdir=$(pwd)  smoketestresults-XXXXXXXX)

ulimit -c unlimited

script=$(readlink -m -- ${0}-actual)

cd ${WORKDIR}

unset SSH_AGENT_PID SSH_AUTH_SOCK SSH_CLIENT SSH_TTY WINDOWID XAUTHORITY XDG_RUNTIME_DIR XDG_SESSION_COOKIE XDG_SESSION_ID

#if test $DISPLAY; then 
#	LANG=C LANGUAGE=C SHELL=/bin/bash LC_ALL=C HOME=${WORKDIR} $SRCDIR/bin/xnest-run ${script} ${SRCDIR} 2>&1
#else
	DISPLAY= LANG=C LANGUAGE=C SHELL=/bin/bash LC_ALL=C HOME=${WORKDIR} xvfb-run --server-args="-screen 0, 1000x2500x24" ${script} ${SRCDIR} 2>&1
#fi

if test -f ${WORKDIR}/result-success; then
	echo PASS
	exit 0
else
	echo FAIL
	exit 0  # FIXME Debug conditions to discover timeout error in 
fi
