#!/bin/sh
set -efu

cd $ADTTMP
cat << EOF | marked -o test.html
An h1 header
============

Paragraphs are separated by a blank line.

2nd paragraph. *Italic*, **bold**. Itemized lists
look like:

  * this one
  * that one

EOF

md=$(md5sum test.html | cut -d" " -f 1)
exp="e30f31a4fbb8c06ba6077034ecae3cde"
echo "expecting $exp, got $md"
test "$md" = "$exp" 
echo "ok"
