#!/bin/sh

ifconfig eth0 down
if [ -f /etc/default/bb-mac-addr ] ; then
	. /etc/default/bb-mac-addr
	ifconfig eth0 hw ether ${MAC_ADDR}
else
	ifconfig eth0 hw ether 8e:37:6f:cb:4d:81
fi
ifconfig eth0 up || true

