#!/bin/sh

testdir="${TMPDIR:-/tmp}/rdoctask"
mkdir -p "$testdir"
rakefile="$testdir/Rakefile"

cat > $rakefile  <<EOF
require 'rake/rdoctask'

task :default do
  puts "Hello, world"
end
EOF

cd "$testdir" && ruby1.8 -S rake -X
