#!/bin/sh

set -e

KEYDIR="/var/lib/apt/keyrings"
KEYRING="$KEYDIR/rcn-ee-archive-2015.gpg"

case "$1" in
    purge|remove|failed-upgrade|abort-install|abort-upgrade|disappear)
    if [ -f $KEYRING ]; then
        rm $KEYRING
    fi

    if [ -d $KEYDIR -a ! -f $KEYDIR/* ]; then
	rmdir $KEYDIR
    fi
    ;;
    upgrade)
	touch $KEYRING
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
