.\" Generated with Ronnjs 0.4.0
.\" http://github.com/kapouer/ronnjs
.
.TH "NODE\-GYP" "1" "March 2013" "" ""
.
.SH "NAME"
\fBnode-gyp\fR \-\- native addon build tool for node
.
.SH "SYNOPSIS"
.
.nf
node\-gyp <command> [args]
.
.fi
.
.SH "DESCRIPTION"
\fBnode\-gyp\fR is a cross\-platform command\-line tool for compiling native
addon modules for Node\.js, taking away the pain of dealing with the
various differences in build platforms\.
It is the replacement to the \fBnode\-waf\fR program, which is removed since
node 0\.8\. Native addons still using a \fBwscript\fR file should definitely
add a \fBbinding\.gyp\fR file to support the latest versions of node\.
.
.P
Multiple target versions of node are supported (from node 0\.6 to the
next released version), regardless of what version of node is actually
installed on your system; \fBnode\-gyp\fR downloads the necessary development
files for the target version\.
.
.SH "COMMANDS"
.
.IP "\(bu" 4
\fBbuild\fR 
Invokes \fBmake\fR/\fBmsbuild\.exe\fR and builds the native addon
.
.IP "\(bu" 4
\fBclean\fR
Removes any the \fBbuild\fR dir if it exists
.
.IP "\(bu" 4
\fBconfigure\fR
Generates project build files for the current platform
.
.IP "\(bu" 4
\fBrebuild\fR
Runs \fBclean\fR, \fBconfigure\fR and \fBbuild\fR all in a row
.
.IP "\(bu" 4
\fBinstall\fR <version>
Installs node development header files for the given version
.
.IP "\(bu" 4
\fBlist\fR
Lists the currently installed node development file versions
.
.IP "\(bu" 4
\fBremove\fR <version>
Removes the node development header files for the given version
.
.IP "" 0
.
.SH "SEE ALSO"
README\.md
