#!/bin/bash

set -e

SRCDIR=$(pwd)
WORKDIR=$(mktemp -d)
trap "rm -rf ${WORKDIR}" 0 INT QUIT ABRT PIPE TERM


# about:settings  Advanced
# "Notify me when the website I am visiting can run as an application"


# check that chrome.tld and chrome.infobars are found (available only to
# extensions e.g. in background pages)


# that for the /proc/<pid>environ for the chromium process is not messed up


# validate that you don't see the "webapps plugin requires your authorization"


echo NOOP
