#!/bin/sh

set -e

# avoid cancelling of "stop" via socket or D-Bus activation
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
    systemctl mask --runtime ti-sgx-ti33x-ddk-um.service
    # stop ti-ipc-dra7xx.service manually since invoke-rc.d currently doesn't
    # deal with masked services (see Bug #717109)
    systemctl stop ti-sgx-ti33x-ddk-um.service || true
fi

#DEBHELPER#

exit 0
