#!/bin/bash

#From: https://github.com/RIOT-Makers/wpan-raspbian/blob/master/usr/local/sbin/create_lowpan

if [[ $EUID -ne 0 ]]; then
  echo "You must be a root user" 2>&1
  exit 1
fi

[ -z "$1" ] && {
  echo "Missing channel!"
  echo "USAGE: $0 <CHANNEL> <PAN ID>"
  exit 1
}

[ -z "$2" ] && {
  echo "Missing PAN ID!"
  echo "USAGE: $0 <CHANNEL> <PAN ID>"
  exit 1
}

CHANNEL=$1
PANID=$2
IPADDR=$3

echo "create_lowpan:CHANNEL:$CHANNEL"
echo "create_lowpan:PANID:$PANID"
echo "create_lowpan:IPADDR:$IPADDR"

# check for wpan0
ip link show wpan0 1> /dev/null 2>&1
if [[ $? == '0' ]] ; then
    echo ". taking wpan0 down"
    ip link set dev wpan0 down
else
    echo "! no wpan device found, exit!"
    exit 1
fi
# check for lowpan0
ip link show lowpan0 1> /dev/null 2>&1
if [[ $? == '0' ]]; then
    echo ". lowpan0 exists"
    ip link set lowpan0 down
else
    echo ". create lowpan0"
    ip link add link wpan0 name lowpan0 type lowpan
fi
#set channel and activate device

###FIXME: I had to unload/reload bcfserial, so the phyX index increased.
#iwpan phy phy0 set channel 0 $CHANNEL
iwpan phy `iwpan phy | grep -m1 wpan_phy | cut -d' ' -f2` set channel 0 $CHANNEL

iwpan dev wpan0 set pan_id $PANID
ip link set wpan0 up
ip link set lowpan0 up
# add IPv6 address
if [ ! -z "$IPADDR" -a "$IPADDR" != " " ]; then
    sleep 1
    echo ". adding IPv6 address $IPADDR to lowpan0"
    ip -6 addr add $IPADDR dev lowpan0
fi
