#!/bin/sh

set -e

service="gcp-iot-demo"

# drop the temporary mask from prerm
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	systemctl unmask --runtime ${service}.service
fi

#DEBHELPER#

exit 0
