#!/bin/sh -e

if [ -w /sys/kernel/uevent_helper ]; then
    echo > /sys/kernel/uevent_helper
fi

if ! grep -E -q "^[^[:space:]]+ /dev devtmpfs" /proc/mounts; then
    mount -n -o mode=0755 -t devtmpfs devtmpfs /dev
fi

SYSTEMD_LOG_LEVEL=notice /lib/systemd/systemd-udevd --daemon --resolve-names=never

udevadm trigger --action=add

mkdir -p /dev/pts
mount -t devpts -o noexec,nosuid,gid=5,mode=0620 devpts /dev/pts

udevadm settle || true
