#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
	net_rcnee=$(cat /etc/apt/sources.list | grep repos.rcn-ee.net || true)
	if [ ! "x${net_rcnee}" = "x" ] ; then
		sed -i -e 's:repos.rcn-ee.net:repos.rcn-ee.com:g' /etc/apt/sources.list
	fi
fi

groupadd gpio --system || true
groupadd pwm --system || true
groupadd eqep --system || true

#DEBHELPER#
