#!/bin/bash

log="bb-usb-gadgets"

#Examples
#https://github.com/linux-usb-gadgets/libusbgx/tree/master/examples
#built_in="gadget-acm-ecm"
#echo "${log} /usr/bin/$build_in"
#/usr/bin/$built_in

#Someday...
#echo "${log}: gt load --off bbb-acm-ncm-rndis.scheme g_multi"
#gt load --off bbb-acm-ncm-rndis.scheme g_multi
##update mac addresss...
#echo "${log}: gt enable g_multi"
#gt enable g_multi

#Working old..
#TODO: generate unique mac address...
echo "${log}: bb-start-acm-ncm-rndis-old-gadget"
/usr/bin/bb-start-acm-ncm-rndis-old-gadget
