#!/bin/sh

if [ -f /etc/default/generic-sys-mods ] ; then
	. /etc/default/generic-sys-mods
fi

if [ ! "x${ROOT_DRIVE}" = "x" ] ; then
	if [ ! "x${ROOT_PARTITION}" = "x" ] ; then
		echo "/usr/bin/growpart ${ROOT_DRIVE} ${ROOT_PARTITION}"
		/usr/bin/growpart ${ROOT_DRIVE} ${ROOT_PARTITION}
	fi
fi
