#!/usr/bin/perl -w

=head1 NAME

dh_nodejs - set nodejs dependencies

=cut

use strict;
use Debian::Debhelper::Dh_Lib;

=head1 SYNOPSIS

B<dh_nodejs> [S<I<debhelper options>>]

=head1 DESCRIPTION

B<dh_nodejs> is a debhelper program that is responsible for generating
appropriate dependencies on nodejs.

The dependency on nodejs will be generated in B<${misc:Depends}>.

=cut

init();

# TODO: add support for generating nodejs:Recommends instead
#my $relation='Depends';
#if (defined $dh{RELATION}) {
#	$relation=ucfirst(lc($dh{RELATION}));
#}

# parse list file
open (RAWFILE, '/usr/share/nodejs/pluginsdep')
	or error("cannot read /usr/share/nodejs/pluginsdep: $!\n");
my $deps = <RAWFILE>;
close RAWFILE;
chomp $deps;

foreach my $package (@{$dh{DOPACKAGES}}) {
	addsubstvar($package, "misc:Depends", $deps);
}

=head1 SEE ALSO

L<debhelper(7)>

This program is a part of nodejs-dev.

=head1 AUTHOR

Jonas Smedegaard <dr@jones.dk>

=cut

