usr/include/polkit-qt5-1/PolkitQt1/ActionDescription
usr/include/polkit-qt5-1/PolkitQt1/Agent/Listener
usr/include/polkit-qt5-1/PolkitQt1/Agent/Session
usr/include/polkit-qt5-1/PolkitQt1/Authority
usr/include/polkit-qt5-1/PolkitQt1/Details
usr/include/polkit-qt5-1/PolkitQt1/Gui/Action
usr/include/polkit-qt5-1/PolkitQt1/Gui/ActionButton
usr/include/polkit-qt5-1/PolkitQt1/Gui/ActionButtons
usr/include/polkit-qt5-1/PolkitQt1/Identity
usr/include/polkit-qt5-1/PolkitQt1/Subject
usr/include/polkit-qt5-1/PolkitQt1/TemporaryAuthorization
usr/include/polkit-qt5-1/polkitqt1-actiondescription.h
usr/include/polkit-qt5-1/polkitqt1-agent-listener.h
usr/include/polkit-qt5-1/polkitqt1-agent-session.h
usr/include/polkit-qt5-1/polkitqt1-authority.h
usr/include/polkit-qt5-1/polkitqt1-details.h
usr/include/polkit-qt5-1/polkitqt1-export.h
usr/include/polkit-qt5-1/polkitqt1-gui-action.h
usr/include/polkit-qt5-1/polkitqt1-gui-actionbutton.h
usr/include/polkit-qt5-1/polkitqt1-gui-actionbuttons.h
usr/include/polkit-qt5-1/polkitqt1-identity.h
usr/include/polkit-qt5-1/polkitqt1-subject.h
usr/include/polkit-qt5-1/polkitqt1-temporaryauthorization.h
usr/include/polkit-qt5-1/polkitqt1-version.h



usr/lib/*/cmake/PolkitQt5-1/PolkitQt5-1Config.cmake
usr/lib/*/cmake/PolkitQt5-1/PolkitQt5-1ConfigVersion.cmake
usr/lib/*/cmake/PolkitQt5-1/PolkitQt5-1Targets.cmake
usr/lib/*/cmake/PolkitQt5-1/PolkitQt5-1Targets-none.cmake
usr/lib/*/libpolkit-qt5-agent-1.so
usr/lib/*/libpolkit-qt5-core-1.so
usr/lib/*/libpolkit-qt5-gui-1.so
usr/lib/*/pkgconfig/polkit-qt5-1.pc
usr/lib/*/pkgconfig/polkit-qt5-agent-1.pc
usr/lib/*/pkgconfig/polkit-qt5-core-1.pc
usr/lib/*/pkgconfig/polkit-qt5-gui-1.pc
