.TH JEKYLL "1" "May 2012" "Jekyll 0.11.2" "User Commands"
.SH NAME
Jekyll \- is a blogaware, static site generator.
.SH USAGE
.TP
jekyll
# . \-> ./_site
.TP
jekyll <path to write generated site>
# . \-> <path>
.TP
jekyll <path to source> <path to write generated site>
# <path> \-> <path>
.TP
jekyll import <importer name> <options>
# imports posts using named import script
.IP
Configuration is read from '<source>/_config.yml' but can be overridden
using the following options:
.SH OPTIONS
.TP
\fB\-\-file\fR [PATH]
File to import from
.TP
\fB\-\-dbname\fR [TEXT]
DB to import from
.TP
\fB\-\-user\fR [TEXT]
Username to use when importing
.TP
\fB\-\-pass\fR [TEXT]
Password to use when importing
.TP
\fB\-\-host\fR [HOST ADDRESS]
Host to import from
.TP
\fB\-\-site\fR [SITE NAME]
Site to import from
.TP
\fB\-\-[no\-]safe\fR
Safe mode (default unsafe)
.TP
\fB\-\-[no\-]auto\fR
Auto\-regenerate
.TP
\fB\-\-server\fR [PORT]
Start web server (default port 4000)
.TP
\fB\-\-no\-server\fR
Do not start a web server
.TP
\fB\-\-base\-url\fR [BASE_URL]
Serve website from a given base URL (default '/'
.TP
\fB\-\-[no\-]lsi\fR
Use LSI for better related posts
.TP
\fB\-\-[no\-]pygments\fR
Use pygments to highlight code
.TP
\fB\-\-rdiscount\fR
Use rdiscount gem for Markdown
.TP
\fB\-\-redcarpet\fR
Use redcarpet gem for Markdown
.TP
\fB\-\-kramdown\fR
Use kramdown gem for Markdown
.TP
\fB\-\-time\fR [TIME]
Time to generate the site for
.TP
\fB\-\-[no\-]future\fR
Render future dated posts
.TP
\fB\-\-permalink\fR [TYPE]
Use 'date' (default) for YYYY/MM/DD
.TP
\fB\-\-paginate\fR [POSTS_PER_PAGE]
Paginate a blog's posts
.TP
\fB\-\-limit_posts\fR [MAX_POSTS]
Limit the number of posts to publish
.TP
\fB\-\-url\fR [URL]
Set custom site.url
.TP
\fB\-\-version\fR
Display current version
.SH AUTHOR
This manual page was written by Youhei SASAKI <uwabami@gfd-dennou.org>, for the Debian GNU/Linux system(but may be used by others).

